package model

import "github.com/google/uuid"

type ExifData struct {
	PhotoID                          uuid.UUID
	Sharpness                        *int
	MakerNote                        *string
	XResolution                      *float64
	ExposureBiasValue                *float64
	ApertureValue                    *float64
	ResolutionUnit                   *int
	ThumbJPEGInterchangeFormat       *int
	Model                            *string
	FocalPlaneXResolution            *float64
	BitsPerSample                    []int
	DeviceSettingDescription         *string
	SubSecTimeDigitized              *string
	ImageLength                      *int
	GPSVersionID                     *int
	XPAuthor                         []int
	MaxApertureValue                 *float64
	ISOSpeedRatings                  *int
	SensingMethod                    *int
	FileSource                       *string
	ExifVersion                      *string
	ImageWidth                       *int
	GPSAltitudeRef                   *float64
	SamplesPerPixel                  *int
	Software                         *string
	Saturation                       *int
	LightSource                      *int
	GPSLatitude                      []float64
	LensModel                        *string
	PixelXDimension                  *int
	UserComment                      *string
	GPSInfoIFDPointer                *int
	ExifIFDPointer                   *int
	ExposureTime                     *float64
	CFAPattern                       *string
	GPSLongitude                     []float64
	Copyright                        *string
	Flash                            *int
	YResolution                      *float64
	MeteringMode                     *int
	InteroperabilityIFDPointer       *int
	GPSAltitude                      *float64
	SceneType                        *string
	ImageDescription                 *string
	BrightnessValue                  *float64
	Artist                           *string
	FocalLengthIn35mmFilm            *int
	ExposureMode                     *int
	WhiteBalance                     *int
	PixelYDimension                  *int
	SubSecTimeOriginal               *string
	DigitalZoomRatio                 *float64
	CompressedBitsPerPixel           *float64
	DateTime                         *string
	GainControl                      *int
	XPKeywords                       []int
	Contrast                         *int
	GPSProcessingMethod              *string
	FocalPlaneResolutionUnit         *int
	ShutterSpeedValue                *float64
	SubSecTime                       *string
	GPSLatitudeRef                   *string
	ImageUniqueID                    *string
	ColorSpace                       *int
	ExposureProgram                  *int
	GPSLongitudeRef                  *string
	DateTimeOriginal                 *string
	ComponentsConfiguration          *string
	FNumber                          *float64
	XPComment                        []int
	XPTitle                          []int
	ThumbJPEGInterchangeFormatLength *int
	YCbCrPositioning                 *int
	Orientation                      *int
	PhotometricInterpretation        *int
	FocalLength                      *float64
	SceneCaptureType                 *int
	Make                             *string
	GPSDateStamp                     *string
	RelatedSoundFile                 *string
	FlashpixVersion                  *string
	CustomRendered                   *int
	DateTimeDigitized                *string
	ExposureIndex                    *float64
	FocalPlaneYResolution            *float64
	InteroperabilityIndex            *string
	SubjectDistanceRange             *int
	GPSTimeStamp                     []float64
}
