package entity

import "github.com/google/uuid"

type ExifData struct {
	PhotoID                          uuid.UUID `db:"photo_id"`
	Sharpness                        *int      `db:"sharpness"`
	MakerNote                        *string   `db:"maker_note"`
	XResolution                      *float64  `db:"x_resolution"`
	ExposureBiasValue                *float64  `db:"exposure_bias_value"`
	ApertureValue                    *float64  `db:"aperture_value"`
	ResolutionUnit                   *int      `db:"resolution_unit"`
	ThumbJPEGInterchangeFormat       *int      `db:"thumb_jpeg_interchange_format"`
	Model                            *string   `db:"model"`
	FocalPlaneXResolution            *float64  `db:"focal_plane_x_resolution"`
	BitsPerSample                    []int     `db:"bits_per_sample"`
	DeviceSettingDescription         *string   `db:"device_setting_description"`
	SubSecTimeDigitized              *string   `db:"sub_sec_time_digitized"`
	ImageLength                      *int      `db:"image_length"`
	GPSVersionID                     *int      `db:"gps_version_id"`
	XPAuthor                         []int     `db:"xp_author"`
	MaxApertureValue                 *float64  `db:"max_aperture_value"`
	ISOSpeedRatings                  *int      `db:"iso_speed_ratings"`
	SensingMethod                    *int      `db:"sensing_method"`
	FileSource                       *string   `db:"file_source"`
	ExifVersion                      *string   `db:"exif_version"`
	ImageWidth                       *int      `db:"image_width"`
	GPSAltitudeRef                   *float64  `db:"gps_altitude_ref"`
	SamplesPerPixel                  *int      `db:"samples_per_pixel"`
	Software                         *string   `db:"software"`
	Saturation                       *int      `db:"saturation"`
	LightSource                      *int      `db:"light_source"`
	GPSLatitude                      []float64 `db:"gps_latitude"`
	LensModel                        *string   `db:"lens_model"`
	PixelXDimension                  *int      `db:"pixel_x_dimension"`
	UserComment                      *string   `db:"user_comment"`
	GPSInfoIFDPointer                *int      `db:"gps_info_ifd_pointer"`
	ExifIFDPointer                   *int      `db:"exif_ifd_pointer"`
	ExposureTime                     *float64  `db:"exposure_time"`
	CFAPattern                       *string   `db:"cfa_pattern"`
	GPSLongitude                     []float64 `db:"gps_longitude"`
	Copyright                        *string   `db:"copyright"`
	Flash                            *int      `db:"flash"`
	YResolution                      *float64  `db:"y_resolution"`
	MeteringMode                     *int      `db:"metering_mode"`
	InteroperabilityIFDPointer       *int      `db:"interoperability_ifd_pointer"`
	GPSAltitude                      *float64  `db:"gps_altitude"`
	SceneType                        *string   `db:"scene_type"`
	ImageDescription                 *string   `db:"image_description"`
	BrightnessValue                  *float64  `db:"brightness_value"`
	Artist                           *string   `db:"artist"`
	FocalLengthIn35mmFilm            *int      `db:"focal_length_in_35_mm_film"`
	ExposureMode                     *int      `db:"exposure_mode"`
	WhiteBalance                     *int      `db:"white_balance"`
	PixelYDimension                  *int      `db:"pixel_y_dimension"`
	SubSecTimeOriginal               *string   `db:"sub_sec_time_original"`
	DigitalZoomRatio                 *float64  `db:"digital_zoom_ratio"`
	CompressedBitsPerPixel           *float64  `db:"compressed_bits_per_pixel"`
	DateTime                         *string   `db:"date_time"`
	GainControl                      *int      `db:"gain_control"`
	XPKeywords                       []int     `db:"xp_keywords"`
	Contrast                         *int      `db:"contrast"`
	GPSProcessingMethod              *string   `db:"gps_processing_method"`
	FocalPlaneResolutionUnit         *int      `db:"focal_plane_resolution_unit"`
	ShutterSpeedValue                *float64  `db:"shutter_speed_value"`
	SubSecTime                       *string   `db:"sub_sec_time"`
	GPSLatitudeRef                   *string   `db:"gps_latitude_ref"`
	ImageUniqueID                    *string   `db:"image_unique_id"`
	ColorSpace                       *int      `db:"color_space"`
	ExposureProgram                  *int      `db:"exposure_program"`
	GPSLongitudeRef                  *string   `db:"gps_longitude_ref"`
	DateTimeOriginal                 *string   `db:"date_time_original"`
	ComponentsConfiguration          *string   `db:"components_configuration"`
	FNumber                          *float64  `db:"f_number"`
	XPComment                        []int     `db:"xp_comment"`
	XPTitle                          []int     `db:"xp_title"`
	ThumbJPEGInterchangeFormatLength *int      `db:"thumb_jpeg_interchange_format_length"`
	YCbCrPositioning                 *int      `db:"y_cb_cr_positioning"`
	Orientation                      *int      `db:"orientation"`
	PhotometricInterpretation        *int      `db:"photometric_interpretation"`
	FocalLength                      *float64  `db:"focal_length"`
	SceneCaptureType                 *int      `db:"scene_capture_type"`
	Make                             *string   `db:"make"`
	GPSDateStamp                     *string   `db:"gps_date_stamp"`
	RelatedSoundFile                 *string   `db:"related_sound_file"`
	FlashpixVersion                  *string   `db:"flashpix_version"`
	CustomRendered                   *int      `db:"custom_rendered"`
	DateTimeDigitized                *string   `db:"date_time_digitized"`
	ExposureIndex                    *float64  `db:"exposure_index"`
	FocalPlaneYResolution            *float64  `db:"focal_plane_y_resolution"`
	InteroperabilityIndex            *string   `db:"interoperability_index"`
	SubjectDistanceRange             *int      `db:"subject_distance_range"`
	GPSTimeStamp                     []float64 `db:"gps_time_stamp"`
}
