package exif_photo_data

var propertyDescription = map[string]string{
	"Sharpness":                        "Резкость",
	"MakerNote":                        "Примечание производителя",
	"XResolution":                      "Разрешение по X",
	"ExposureBiasValue":                "Компенсация экспозиции",
	"ApertureValue":                    "Значение апертуры",
	"ResolutionUnit":                   "Единица разрешения",
	"ThumbJPEGInterchangeFormat":       "Формат JPEG для миниатюры",
	"Model":                            "Модель",
	"FocalPlaneXResolution":            "Фокусное разрешение по X",
	"BitsPerSample":                    "Бит на образец",
	"DeviceSettingDescription":         "Описание настроек устройства",
	"SubSecTimeDigitized":              "Время цифровой обработки (до секунды)",
	"ImageLength":                      "Длина изображения",
	"GPSVersionID":                     "Версия GPS",
	"XPAuthor":                         "Автор XP",
	"MaxApertureValue":                 "Максимальное значение апертуры",
	"ISOSpeedRatings":                  "Скорость ISO",
	"SensingMethod":                    "Метод измерения",
	"FileSource":                       "Источник файла",
	"ExifVersion":                      "Версия Exif",
	"ImageWidth":                       "Ширина изображения",
	"GPSAltitudeRef":                   "Ссылка на высоту GPS",
	"SamplesPerPixel":                  "Образцов на пиксель",
	"Software":                         "Программное обеспечение",
	"Saturation":                       "Насыщенность",
	"LightSource":                      "Источник света",
	"GPSLatitude":                      "Широта GPS",
	"LensModel":                        "Модель объектива",
	"PixelXDimension":                  "Размер пикселя по X",
	"UserComment":                      "Комментарий пользователя",
	"GPSInfoIFDPointer":                "Указатель на GPS IFD",
	"ExifIFDPointer":                   "Указатель на Exif IFD",
	"ExposureTime":                     "Время экспозиции",
	"CFAPattern":                       "Паттерн CFA",
	"GPSLongitude":                     "Долгота GPS",
	"Copyright":                        "Авторское право",
	"Flash":                            "Вспышка",
	"YResolution":                      "Разрешение по Y",
	"MeteringMode":                     "Режим замера",
	"InteroperabilityIFDPointer":       "Указатель на интероперабельный IFD",
	"GPSAltitude":                      "Высота GPS",
	"SceneType":                        "Тип сцены",
	"ImageDescription":                 "Описание изображения",
	"BrightnessValue":                  "Значение яркости",
	"Artist":                           "Художник",
	"FocalLengthIn35mmFilm":            "Фокусное расстояние для 35мм пленки",
	"ExposureMode":                     "Режим экспозиции",
	"WhiteBalance":                     "Баланс белого",
	"PixelYDimension":                  "Размер пикселя по Y",
	"SubSecTimeOriginal":               "Оригинальное время (до секунды)",
	"DigitalZoomRatio":                 "Коэффициент цифрового зума",
	"CompressedBitsPerPixel":           "Сжатые биты на пиксель",
	"DateTime":                         "Дата и время",
	"GainControl":                      "Управление усилением",
	"XPKeywords":                       "Ключевые слова XP",
	"Contrast":                         "Контраст",
	"GPSProcessingMethod":              "Метод обработки GPS",
	"FocalPlaneResolutionUnit":         "Единица разрешения фокусной плоскости",
	"ShutterSpeedValue":                "Значение скорости затвора",
	"SubSecTime":                       "Время (до секунды)",
	"GPSLatitudeRef":                   "Ссылка на широту GPS",
	"ImageUniqueID":                    "Уникальный ID изображения",
	"ColorSpace":                       "Цветовое пространство",
	"ExposureProgram":                  "Программа экспозиции",
	"GPSLongitudeRef":                  "Ссылка на долготу GPS",
	"DateTimeOriginal":                 "Оригинальная дата и время",
	"ComponentsConfiguration":          "Конфигурация компонентов",
	"FNumber":                          "Число F",
	"XPComment":                        "Комментарий XP",
	"XPTitle":                          "Название XP",
	"ThumbJPEGInterchangeFormatLength": "Длина формата JPEG для миниатюры",
	"YCbCrPositioning":                 "Позиционирование YCbCr",
	"Orientation":                      "Ориентация",
	"PhotometricInterpretation":        "Фотометрическая интерпретация",
	"FocalLength":                      "Фокусное расстояние",
	"SceneCaptureType":                 "Тип захвата сцены",
	"Make":                             "Производитель",
	"GPSDateStamp":                     "Дата GPS",
	"RelatedSoundFile":                 "Связанный звуковой файл",
	"FlashpixVersion":                  "Версия Flashpix",
	"CustomRendered":                   "Пользовательская обработка",
	"DateTimeDigitized":                "Дата и время цифровой обработки",
	"ExposureIndex":                    "Индекс экспозиции",
	"FocalPlaneYResolution":            "Фокусное разрешение по Y",
	"InteroperabilityIndex":            "Индекс интероперабельности",
	"SubjectDistanceRange":             "Диапазон расстояния до объекта",
	"GPSTimeStamp":                     "Метка времени GPS",
}
