server:
  host: "localhost"
  http_port: 8080
  grpc_port: 8181
  max_send_message_length: 2147483647
  max_receive_message_length: 63554432
  shutdown_timeout: 3

pg_db:
  conn_string: "postgresql://root:q9ckMfi6xQUc1@10.10.10.201:5501/photos?sslmode=disable"

fs_store:
  base_files_dir: "Y:\\documents\\photos_storage"

photo_ml:
  url: "http://127.0.0.1:5000"

processing_photo:
  max_goroutines: 16

similar_photo:
  limit: 1000
  min_similar_coefficient: 0.75

photo_group:
  min_similar_coefficient: 0.95

photos:
  photo_server_url: "http://localhost:8080/photos"