server:
  host: "localhost"
  http_port: 8080
  grpc_port: 8181
  max_send_message_length: 2147483647
  max_receive_message_length: 63554432
  shutdown_timeout: 3

pg_db:
  conn_string: "postgresql://root@localhost/photo_library?sslmode=disable"

fs_store:
  base_files_dir: "D:\\photo_library"
  photo_server_url: "http://localhost:8080/photos"

photo_ml:
  url: "http://127.0.0.1:5000"

processing_photo:
  max_goroutines: 16
  limit: 100
  debug: false

similar_photo:
  limit: 1000
  min_similar_coefficient: 0.75
  debug: false

photo_group:
  min_similar_coefficient: 0.95
  debug: false

photo_preview:
  sizes:
    - 480
    - 640
    - 800
    - 1024
    - 1200
    - 1440
    - 1620
    - 2048